### ISSUE TITLE
Need to add model extent to new models in INSTAR

### ISSUE THREAD

**Issue by daniel-nelson-namc** [namc-utah/instar.namc-usu.org#4]
New models in INSTAR need model extent added. Models are SC_2023 (301), TN_2023 (302), TP_2023 (303). The model extents are in the extent description box. Thanks.

**Comment by philipbaileynar** [comment]
@daniel-nelson-namc what would be the existing model that has the closest extent to these new models?

**Comment by philipbaileynar** [comment]
Looks like I can use the model extent for WestWide and remove the Xeric regions? (i.e. fill in the hole in this existing model extent)

<img width="1149" alt="Screenshot 2023-07-26 at 11 49 30 AM" src="https://github.com/namc-utah/instar.namc-usu.org/assets/8645379/50500442-7fd0-423c-88cd-7602f1d16d45">

**Comment by daniel-nelson-namc** [comment]
I believe the extent of the current EC12 model (model Id 29) would work for these new models. Thanks.

**Comment by philipbaileynar** [comment]
The following SQL was executed on production at 12:00 PST on 26 Jul 2023:

```sql
UPDATE geo.models
SET extent = models2.extent
FROM geo.models models2
WHERE models2.model_id = 29
  AND geo.models.model_id in (301, 302, 303);
```
